name: "ixp-agent" # name of the rpm package
arch: "amd64"     # architecture you are using
version: "v1.0.1" # version of this rpm package
maintainer: "Jeroen van Bemmel <jeroen.van_bemmel@nokia.com"
description: Agent to automatically configure BGP peering based on PeeringDB and IRR queries
vendor: "Nokia"     # optional information about the creator of the package
license: "Apache 2.0"
contents:                              # contents to add to the package
  - src: ./rpmbuild
    dst: /opt/     # destination path (including yang)

  - src: ./ixp-agent.yml    # local path of agent yml
    dst: /etc/opt/srlinux/appmgr/ixp-agent.yml
